blueprint:
  name: Azan Notifications
  description: Play Adhan audio and send notifications at prayer times.
  domain: automation
  input:
    # 🎧 Audio Settings
    media_player_target:
      name: 🖥️ Target Media Player
      description: Speaker or display that will play the Adhan.
      selector:
        entity:
          domain: media_player

    volume_level:
      name: 🔊 Volume Level (0.0 to 1.0)
      description: Set the playback volume before Adhan (optional)
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

    media_player_type:
      name: 🎛️ Media Player Type
      description: Choose the type of media player service call
      default: "media_play"
      selector:
        select:
          options:
            - label: "Media Play"
              value: "media_play"
            - label: "Play Media"
              value: "play_media"

    adhan_url:
      name: 📁 Adhan Media URL
      description: Full URL or path to the Adhan mp3 file
      default: "/local/adhan.mp3"
      selector:
        text: {}

    # 🔔 Enabled Prayers
    fajr_enabled:
      name: 🌅 Fajr Prayer
      description: Enable or disable Fajr notifications
      default: true
      selector:
        boolean: {}

    dhuhr_enabled:
      name: ☀️ Dhuhr Prayer
      description: Enable or disable Dhuhr notifications
      default: true
      selector:
        boolean: {}

    asr_enabled:
      name: 🌤️ Asr Prayer
      description: Enable or disable Asr notifications
      default: true
      selector:
        boolean: {}

    maghrib_enabled:
      name: 🌇 Maghrib Prayer
      description: Enable or disable Maghrib notifications
      default: true
      selector:
        boolean: {}

    # 💬 Notification Messages
    fajr_message:
      name: Fajr Custom Message
      default: "Time for Fajr prayer – حان الآن موعد صلاة الفجر"
      selector:
        text: {}

    dhuhr_message:
      name: Dhuhr Custom Message
      default: "Time for Dhuhr prayer – حان الآن موعد صلاة الظهر"
      selector:
        text: {}

    asr_message:
      name: Asr Custom Message
      default: "Time for Asr prayer – حان الآن موعد صلاة العصر"
      selector:
        text: {}

    maghrib_message:
      name: Maghrib Custom Message
      default: "Time for Maghrib prayer – حان الآن موعد صلاة المغرب"
      selector:
        text: {}

    # 📲 Notification Target
    notify_device:
      name: 📲 Mobile Device
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: false

    # 🕌 Prayer Time Sensors
    fajr_sensor:
      name: 🌅 Fajr Time Sensor
      description: Select a sensor that provides the Fajr prayer time.
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: timestamp

    dhuhr_sensor:
      name: ☀️ Dhuhr Time Sensor
      description: Select a sensor that provides the Dhuhr prayer time.
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: timestamp

    asr_sensor:
      name: 🌤️ Asr Time Sensor
      description: Select a sensor that provides the Asr prayer time.
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: timestamp

    maghrib_sensor:
      name: 🌇 Maghrib Time Sensor
      description: Select a sensor that provides the Maghrib prayer time.
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: timestamp

# Trigger/action/condition logic would go here
